services:
  postgres:
    image: postgres:17

    container_name: design_struct_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: design_struct

    ports:
      - '5400:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data
  swagger:
    image: swaggerapi/swagger-ui

    container_name: design_struct_swagger

    ports:
      - '8081:8080'

    environment:
      SWAGGER_JSON: /docs/openapi.yaml

    volumes:
      - ./docs:/docs

volumes:
  postgres_data:
